server:
  port: 8090
  servlet:
    context-path: /kapetanios/v1

app:
  datadog-config:
    api-url: https://api.datadoghq.com/api/v1/query
    api-key: 09ae75edc10ec7e8eb3356dd903dd9ba
    application-key: e542b10fc533211c55d23b6cf5759f6a93076b60


management:
  datadog:
    metrics:
      export:
        enabled: true
        api-key: 6af6ab344be0a4b606166ce267674556
        application-key: e542b10fc533211c55d23b6cf5759f6a93076b60
        host-tag: kapetanios
        step: 1m
