apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-clusterrolebinding
  namespace: kapetanios
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: kapetanios
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
