apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kapetanios-agent.fullname" . }}
  namespace: kapetanios
  labels:
    {{- include "kapetanios-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kapetanios-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kapetanios-agent.selectorLabels" . | nindent 8 }}
    spec:
      # Asegura que DNS funcione correctamente
      dnsPolicy: "ClusterFirst"
      # Permite tráfico saliente
      hostNetwork: {{ .Values.network.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: kapetanios-agent-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-sa