apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kapetanios-agent.fullname" . }}-network-policy
  namespace: kapetanios
  labels:
    {{- include "kapetanios-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kapetanios-agent.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - {}  # Permite todo el tráfico saliente sin restricciones 