apiVersion: v1
kind: ConfigMap
metadata:
  name: kapetanios-agent-config
  namespace: kapetanios
data:
  PROMETHEUS_URL: "http://localhost:9090"
  MODEL_API_URL: "http://localhost"
  KAPETANIOS_SERVER_URL: "http://localhost:8085"
