apiVersion: v1
kind: Service
metadata:
  name: kapetanios-sample-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: kapetanios-sample-app